# frozen_string_literal: true

ENV['SEQUENT_ENV'] ||= 'development'

require './my_app'
require 'sequent/rake/migration_tasks'

Sequent::Rake::MigrationTasks.new.register_tasks!

task 'sequent:migrate:init' => [:db_connect]

task 'db_connect' do
  Sequent::Support::Database.connect!(ENV['SEQUENT_ENV'])
end
