language: ruby
env:
  matrix:
    - "ACTIVE_STAR_VERSION='~> 5.0.0'"
    - "ACTIVE_STAR_VERSION='~> 5.1.0'"
  global:
    - CC_TEST_REPORTER_ID=90d155b5365c78e09124561d299cb88a6da9ea595e3d2f7c2cff68dfb5100599
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)
    - COVERAGE=true
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.0
  - 2.5.1
addons:
  postgresql: "9.6"
before_script:
  - psql -c 'CREATE USER sequent NOSUPERUSER NOCREATEDB NOCREATEROLE;' -U postgres
  - psql -c 'CREATE DATABASE sequent_spec_db OWNER sequent;' -U postgres
  - bundle exec rake db:create
#  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
#  - chmod +x ./cc-test-reporter
script:
  - bundle exec rspec
#  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_RUBY_VERSION" == "2.2.2" ] && [ "$ACTIVE_STAR_VERSION" == "~> 5.1.0" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
