language: ruby
rvm:
  - 2.1.5
  - 2.2.2
env:
  - "ACTIVE_STAR_VERSION='~> 4.2'"
  - "ACTIVE_STAR_VERSION='~> 5.0.0'"
script: bundle exec rspec
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'CREATE USER sequent NOSUPERUSER NOCREATEDB NOCREATEROLE;' -U postgres
  - psql -c 'CREATE DATABASE sequent_spec_db OWNER sequent;' -U postgres
  - bundle exec rake db:create
