\ir migrate/sequent/aggregate_event_type_v01.sql
\ir migrate/sequent/enrich_command_json_v01.sql
\ir migrate/sequent/aggregates_that_need_snapshots_v01.sql
\ir migrate/sequent/command_records_v01.sql
\ir migrate/sequent/delete_all_snapshots_v01.sql
\ir migrate/sequent/delete_snapshots_before_v01.sql
\ir migrate/sequent/enrich_event_json_v01.sql
\ir migrate/sequent/event_records_v01.sql
\ir migrate/sequent/load_event_v01.sql
\ir migrate/sequent/load_events_v01.sql
\ir migrate/sequent/load_latest_snapshots_v01.sql
\ir migrate/sequent/permanently_delete_commands_without_events_v01.sql
\ir migrate/sequent/permanently_delete_event_streams_v01.sql
\ir migrate/sequent/save_events_trigger_v01.sql
\ir migrate/sequent/select_aggregates_for_snapshotting_v01.sql
\ir migrate/sequent/store_aggregates_v01.sql
\ir migrate/sequent/store_command_v01.sql
\ir migrate/sequent/store_events_v01.sql
\ir migrate/sequent/store_snapshots_v01.sql
\ir migrate/sequent/stream_records_v01.sql
\ir migrate/sequent/update_types_v01.sql
\ir migrate/sequent/update_unique_keys_v01.sql
