source 'https://rubygems.org'

gem 'faraday', '1.10.6'
gem 'webrick'
gem 'ostruct'
gem 'dotenv', groups: [:development, :test]

group :jekyll_plugins do
  gem 'github-pages'
  gem 'jekyll-feed'
  gem 'jekyll-include-cache'
  gem 'jekyll-sitemap'
end
