source 'https://rubygems.org'

gem 'faraday', '1.8.0'
gem 'minima', '~> 2.0'
gem 'webrick'
gem 'ostruct'

group :jekyll_plugins do
  gem 'github-pages'
  gem 'jekyll-feed'
  gem 'jekyll-include-cache'
end
