source 'https://rubygems.org'

gem 'jekyll', '~> 4.4'
gem 'webrick'

group :jekyll_plugins do
  gem 'jekyll-feed'
  gem 'jekyll-include-cache'
  gem 'jekyll-remote-theme'
  gem 'jekyll-sitemap'
  gem 'jemoji'
end
